### PR TITLE
Dependency upgrades

### PR DESCRIPTION
**Pull request by micronaut-build**
Upgrades dependencies to their latest versions

### CODE REVIEW

**Comment by schernolyas** [comment]
Hi @graemerocher !

Could you provide maintainer rights for @pollend ? Points of view on my customer was changed. I haven't possibility to work on the project.

**Comment by pollend** [comment]
I believe the apache ignite developers were going to work on a configuration when I last talked to @graemerocher. not sure where this stands or what should i be working on in terms of ignite and micronaut.

**Comment by graemerocher** [comment]
@pollend seems that is no longer the case. If you still want to take this project forward let me know, otherwise I think we can just delete it since we don't have the bandwidth to undertake this project right now

**Comment by pollend** [comment]
If that is the case, then I can work on this some more. The basic configuration is there, just need to refine what I have so far and then think about building out features.

**Pull request closed without merging**
